# Generated by Django 4.2.18 on 2025-02-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_comments_alter_track_genre_alter_track_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='comments',
        ),
    ]
