# Generated by Django 4.2.18 on 2025-02-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_alter_track_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('in_review', 'In Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved')], default='not_reviewed', max_length=25),
        ),
    ]
