# Generated by Django 4.2.18 on 2025-02-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_track_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='review_status',
        ),
    ]
