# Generated by Django 4.2.18 on 2025-03-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0009_track_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="album",
        ),
    ]
