# Generated by Django 4.2.18 on 2025-02-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_editor',
            new_name='is_composer',
        ),
    ]
