# Generated by Django 4.2.18 on 2025-02-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0002_genre_mood_projecttype_delete_instrument_and_more"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_comments",
                to="tracks.track",
            ),
        ),
    ]
