# Generated by Django 4.2.18 on 2025-02-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='instrumentcategory',
            options={'ordering': ['name']},
        ),
    ]
