# Generated by Django 4.2.18 on 2025-02-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
